package hu.danos.dicegames.Kamu;

/**
 * Created by danos on 2018. 05. 11..
 */

public enum KamuUIDataType {
    MESSAGE, ROUND,BOT1DICE,BOT2DICE,BOT3DICE,PLAYERDICE, BOT1SAYS, BOT2SAYS, BOT3SAYS, PLAYERSAYS, BOT1BELIEVES, BOT2BELIEVES,BOT3BELIEVES,PLAYERBELIEVES, BOT1ELIMINATED, BOT2ELIMINATED, BOT3ELIMINATED, STATE_SAY, STATE_BELIEVE, STATE_WAIT, PLAYERWINS, PLAYERLOSES

}
