package hu.danos.dicegames.Bazs;

public enum UIDataType {
	MESSAGE, ROUND, TABLEPOINTS,PLAYERPOINTS, BOT1POINTS, BOT2POINTS, BOT3POINTS, BOT1SAYS, BOT2SAYS, BOT3SAYS, PLAYERSAYS, BOT1BELIEVES, BOT2BELIEVES,BOT3BELIEVES,PLAYERBELIEVES, STATE_ROLL, STATE_BELIEVE, WON
}
